controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.aknuk.dev
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYTcyRXRyYVpTWndrMzBS
        N3Y2TzFxajRUNy9ZRTVYME5rWW5HRVRxUnlnCm9FY1hvTHhiTHFFZG1XTUtMWVha
        M1NPOVlreWlYejRNU3hkQWJ1MklXSE0KLS0tIHpjd0NwWmhXRzRvb3lTUUl0ak9Z
        VWUrK2l1TGNQcFZRNHBEVDI2Z3lsMUUKCsqlK4WfWJ0d62+Z3mhSE6R6qzn3sgqb
        KDYKmwAhDtldgOEnNxZ4JSLSFVaZ0JvR4qu8us91tZ/7HRe7GAQ7xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:18:05Z"
  mac: ENC[AES256_GCM,data:Ki/zpXqMFRnKM1/jfTE8H/JlsKnuGpWnS6AqAYK9b2M9L2kBHrIjSBrN0foe6JfFnUIKmHRAjwyu87g0s/884NutNr788nGXGU3LrS+CcZZSXtzi5bGRpLENIttscF1vt4XoDOg0bE9Jl7HdIyfR8jEfPWNFy7VZ4fXZpEwg274=,iv:qmso08GwvM4vBNprZ7WRwlSQugDGsJVl5r5j4ybM2PA=,tag:3EPOqTsukeShY8QdlXTUdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
