controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.aknuk.dev
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbWYxSnNndVUwRkpIZ1hM
        ZXpZWDVBSHJyT2lnaVlEZmQ4ejVaSTZvRTNJCit5NkFRbkFHTmd6Q05zRHlsRXYx
        T3lIc0dOeldkbjNYb2pJVXpuWHB1bVkKLS0tIEtNZzRjQkhUR1o2UTJjS3AwSDV0
        M0VrZFNpbytUOExFbzJpWWlsajJtcWsKuHFzdUHpfZ9VmDgGHjlewmWugC6yeiQu
        QNyOj6QwAvcC4kwd2V6x7ZPB5QeBhg/A46h51J5FkJ78puDpWw3X7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T14:17:33Z"
  mac: ENC[AES256_GCM,data:damGCeQw2TlsP6T1yOJuaVvsiPpvmRKOfLP1dGzb3Azxf6cnBj5SpOJ91zrC2XEX+QjrXy3cFFwVu4zlr19oFMOrTcyKiIfRrKT+DfN1gUS4V0UPMo6GnMLmCvATvJZKqeLli92d3HrGPI8DA0meqLSCShoHTNenpLeAwdGDt2k=,iv:t0T5GnaIeHxaI/O1zXZ6EB9I0mzrt8Lr+2+2f+QRldA=,tag:prU/gJtKnaZUVCOYuSTB3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
