controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.aknuk.dev
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZVNHMjlLSkVWSEw5ZWtR
        a2M2b1B4aFNWeGtRWjBsYSszTFp0M0YvUVVZCk1BK1NoUldaYW56UFRHbzF3SFk1
        cVVtV3p0aFN6VHBxaDNFYXVjZmo5OFUKLS0tIHg2bll5YnJjT1MvcVhIZjNkY2tk
        ZGVZb1JvSXFQOXZoL2JsUDBUZTV4U3cK0k0PP+Cd6Z6N+hdymuWnqq+/JuHdFSKg
        Vv3XtLXVs2Ofb/fkY+v56z6RfrXvZmE0Zvo6nuCU5205UAlvpxucPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T15:47:26Z"
  mac: ENC[AES256_GCM,data:pnoz6C222HHUNBQWCkt4aiHCavZ12RYCfns4jrp47RFUDCNV3GYys6mLDHbSifYI9dbvNyWrrtZoPq6bm8W8+zB0oKKj1xFMY23+unX/V2dTIlKJyZDnFtrU+2XgKuEwvWPvUly59jBYU5L0nhy+H5Z+iPv0RUEOwePqXVqU3Vs=,iv:HtxRFRo0XwKCaVA7G2VMqpYg8cJAc6XcpctsgS3rOBc=,tag:PdLUDeo7J+R+Mk9y+H6U2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
