controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 37
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.aknuk.dev
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQmVaclZPZ3NqU1VDMXZ1
        S1lKTGM5NHpUWHFoVEdGek54YjlVOExJK1h3ClhISThnNThrYVlBekwxSlN5RDRv
        RzY0UFdmSFFvclV2M2l2djcwTURmYW8KLS0tIE9yM0NweVNiRzZsM3RmbitGU3pS
        Z1hkUlhkbjZHSTBDcHVBdi9sRjNhcVkKoOq8MFoo95baLk6HUYbsGHuvpIvDEQp4
        DjE90JnL6eNlDGVUwqMPtdtqkIGOTi4Qzn93Mk5SYwSDgRpKXViosA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:44:11Z"
  mac: ENC[AES256_GCM,data:q6IwllbMyuXS/OqzdwnVWbN2zWDGobewsSczsi+bA8QZM2mkHWr7mTN51ttUdYXsF9Bc84T554rimcg4xIWk38lTvaiKguJzZoj95mS84EB6BZ7eJJzXcuQIzwUAX4Sp4Vcd6aBuLf8s3rPbjlDQm6f5tTwoLUY3u9MlMYmbVws=,iv:IsVoMmil5SBdA5iC4KvsDvGEx/nfr2oSG1JyHAbzxRc=,tag:7B2q1i9Awxqj4qxOqhIauA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
