# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:SxwH,iv:J4EmuUXM2VEZhnoV7Yag0eLC/tCUmN4reth3i6sHJwQ=,tag:g0oRc3rnXiusrqlCX9gfPQ==,type:str]
  url: ENC[AES256_GCM,data:i5l6ChCAuYU4ZDfiuwN7Ad0ddE6QfimNyS/gHcqq/C8s/THhOCNgBI8r,iv:0rqIzmTUNxfNrwk1iUMi2Y/t/nrToYSNk3fK8ckgt6A=,tag:K8Xl4Yk4bI3gG7cz+F7LZA==,type:str]
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NlcwdHM4azZzenM5NkNj
        bmhreHFOamVtU2d0dW9mYndBcnZQREZwT3pzCnRoSjlEMzBkdy9vNG1DVy9tT09t
        SG1lYTU4cFNGUHNzTmxOdkdCWS90M3MKLS0tIGo2WUJ0RVFQdmo1QXJUalhUTU5j
        MnVkelpna1k3a0Q4OVF0NXlRd2dNdTgKRjXSxoyK7u/tcDWCEV+5TVdqcI23M1aQ
        Mk7kK71u+ue0auCpS8/6mhSS7IIcprB+8iJblV7CY/STlz9ghS6NGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:44:10Z"
  mac: ENC[AES256_GCM,data:Og0DmJqtDYv20sfLDY9c5uZv1BIoLsYCVs5yKsRCfslmeQxABdzDbbq8MeGzGpSlRRTvbKmV7Om9PBBaPu4dvccqDxH8CdN8NTpkcyDCWFGqNDCNDb+dT11Wb0nkZRs1zwEGht6uxZlp5KZxjqcfP+IQNS/AvbSyIGwsNrX7EwA=,iv:+kB5kuE1iNUSNMPLXUcIopwvwWiQzvGizsI3PZ6L9P8=,tag:sE3O3zSd2xOykZ3Qt6qtvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
