# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:8a3n,iv:v8FWRyH6OQKWTpomO0hlJj6VLeYUtayXZadchTFdu3I=,tag:ry8VFetEHMBjEy7WMxUU+w==,type:str]
  url: ENC[AES256_GCM,data:9wKGqAhTwr8oQMpf04kA3Qh4XYHsPaL1qyeKoyDNgshAUmXeyLN4zbWv,iv:AFJgNxxd6UGBM0n8V9PZSPwnpEECu4Z5Dn6PrIFi+lo=,tag:Y3z8U7B1dLI89HhcDlXP+Q==,type:str]
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMVFrUk1hL2VEU2FJeWVT
        WEJVYWFxTGJXTm5Td003dlVYM1RMUldZeUEwCmxxcytrVmRGM05HUW4vQlBzcVRG
        Y3lYMEl1OHR5VG0wWXUvckpXTE15V3MKLS0tIGY4bEo4K3JNQ2E0azdYcVZ0blZa
        Ynk2dHNMMmFKd0M3Rjl3Tm4wZ0gvR3cKT4pVm/fGKRXtX3DvbFIQkj05VJTpt7HL
        bcqL59FbzwFz17ZzqzfiOy3z8PIKv+k5Q86Ty2xlN8VPZw9zzPh7LQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T15:47:25Z"
  mac: ENC[AES256_GCM,data:1I79UZ+fvh5rj7OA1iFzQmihgnK7/oZmW5sd708A7SkyOgBmOsIsfMwhuMlwvpsWR+szMkzceDX7UZj2XBKcOJGceqg9J0DD7gNCxCoWO1uAdVn+UWjjDuggMTiS8y3r4WTEa6s/8uioEIfCi+iuAmJYAD3efitGokebXW7YZBI=,iv:uJA9KgUmlVh6Owha0m1joRgyDxGpk9oVFONpJ5vyjOE=,tag:ABx5/gdyJ6TOZ4IQVFlUrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
