# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVExEODNqcjY0UkpjMlFs
        TkNmQXlnY3h0bkZVV0ZVcGw1UnN1MStic3hRCjVyRTM4dUcxLzFNbjNNY1F6WkpI
        SEJXSlZlQUlkYmkzYTNhZDR3aVVtYUEKLS0tIFF6MkpRNVBzVnJzbG9JaitxT1Av
        MkdreFRiNm5BbDlqRTRQL3J4R3oxb1kKnLdaOkQ6QAI0abAfh1jqXiQlC2LmXllK
        GDnc9b/d2OzGRYHR7X+6hbqGDcje6NMcR4dCr5ol8wIQUzEPmtdsIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:44:11Z"
  mac: ENC[AES256_GCM,data:blf+VcjqQvYCNaqb8UuFekCQDdYUXyw6b/6rqIuXDit1CNljDVK1j1pOQ1JP0/EAMWkPCn5phTIL5xnhQ0IhSyD3bldn4wFriOIPxwP32fis7X1jyp4O3OHgEztRaKXdwhTWItlG3tWGoYpuEKTRI+65NVwfMmNfLdm/TR8cz9A=,iv:9XzbukCfXPEwgYqQNdhq6EwuhFuJS8ymskh6SgKigqs=,tag:4XD+HQvqxuyT3GZpGVH0Nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
