# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaUg3TW8vSzNTTldTYlJI
        b2RxSGQ0dyt5bWlrUC9pTHcrbDhtUHl0T2lnClNLOFJ6d0twUkFkUFBzamN0RFpn
        a2VLL01ERFRGOHFZRDM4aXk0Uy9ZZ0kKLS0tIHhXTjhVeHlJdmhWRGt5endGK3pY
        c0xwajNpbFFYOEZGUHdlbjJ4TEVqVkEKOX1Axw82u5oegHyButynIkS1xGTqs8TX
        95YhhXwDnq8wjD7TACEeGSg2gK77Lkq/yvXU8UKyKqE1ngdHMBqVNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:18:05Z"
  mac: ENC[AES256_GCM,data:0klyAwlmePrtKlupaIo7L/KaEcA1kXNDXfXbexzWt6knFXQ6T6SvlGmT+U4Wq/OPFzQ1hH9Duuqd9r92StiQc+p13dzdPzjHhqkihe+J/FD3kIht9S1Rq2h3JErSE95zkx6jkGGlTWfVqoIY1vHLVlTu4Ol/abuMLVynIu4TflQ=,iv:XUInqsdmGRwYTON2sH0RK4Pn/cBvhwq/YhFFyQ9LXyQ=,tag:Hb0a5zYsbeyJktDo10Rn3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
