# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa2pQZjdXaVg1cGFuR0dv
        a3BnbEFiVGtuQllFSXRwcEtlbHZIYnRWYVRJCkpzOEp2TGtGMTNFRVVNOVlLMDlL
        Sm4xSzVKZzlQcjhyQWlKNkN6c3lJZVEKLS0tIHNWa2c2VnE4SkJCQnRQUnYrNzdo
        blV2bUlXK0RENHRXSjAyUTJLVXd3Z0UK6EQWjZ72bDNq6WuXf3kx1hMK10IC6B2B
        pTS8BomputgEryDd/5kWlz9DqsWJnf+37IPBqssYR1T5Oz9ZCjkvTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T14:17:32Z"
  mac: ENC[AES256_GCM,data:EM4IY8uLMKJRNN4c47Y9v9uUIUKDzQ1wcjUDfrQi5VKg/lIFuyAj1LxCBWFA52lfbumOYj0fkI6t1NvY9sJSoFiP1sACh/SHqS7TPjmh62zGDsxkbRJ1eXow4rvp0cMUvM18k1MK7SkEHhSbteQqvHNIQuwgiNpkT7tNoh+/PWM=,iv:7dgUq1KoLpCKdYv56/9FRknA0N13xhasRG2r8NZSJQ0=,tag:Pfk9ak6gABDpJlmfukRYOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
