# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0anNtN0x5N2hNMzJiSXFN
        akQ3QWhnUXRYSjJhcVU4VDlucUVRTlI4bm5RCjZFV0ZTcStBbU9LRGJZMkN6NS9Z
        ZUlRV2hoTHV5eWMyRlJMZHlGSzAwdEEKLS0tIGZzT0tXK0JNUk9MMTFwZW5IdTVh
        ZXpXT2hYTTdzRmxwd3JneG1oQmFtcEUKwCKNm2euYv68rCavvFESJ6FlEHL6766N
        vSJM3ddDFVgbdOtN/aGWh+C0pQM6e/BsNnKPTNbI39FTfRqiGQ/jMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T15:47:25Z"
  mac: ENC[AES256_GCM,data:INHSUVeUuki0bXVeZIJKNBrA2aLm4sb9lOQcTd1hvfsWyqJnvtR3CcKAwX3FNBf4bRimOfWnzZ+svbFvWkF211+kvKix23OZj4HwuqhVXFfrLh7OqQF7xFaSCivewE6S1GrVoZVLOLyD/OH/c8kgcq1F8GzXwp+iCYd0yNuaym0=,iv:NggFDljA4gey86oy0pmliRL3e/Pjq/Xb1w79wdhPCFY=,tag:/ZJ+mYortln8Lv8K32phdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
