# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:1LmuOIyisdj3CZtPTkRQJYSew83blJRzmXTU5ubiwSGdagX+iJcRVQ==,iv:ehitEyBwzvuSvNRs3B0qlrp66nPex8CdovCQHqUC4FY=,tag:1ZpqG1w908OS72opqSNFnA==,type:str]
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cjJKTzdsQkxDR2YzV0ly
        NG1zdkJVNWdnWU1HK3lIWDZiRUc4SHZReEd3Cnh4dWJsZHk4WWpiWUFZRnVZamh1
        T2dobGRkM2piV0hCMjNzWmYvMk81R2cKLS0tIFZyd1BUU1ZpcDdNWGJHeFpNOU5Q
        ZDdoRmpPd3VWUjJtN1krRDMwM0RUa00KJ1zFQvaQiO9GeNQe5fkGDWKxqB3b2y+3
        GbpedYkipOuYWWqKJpzZzq+vdyzJ+dcJ7U/7X6lAw1YjOUvehWHmOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T15:47:25Z"
  mac: ENC[AES256_GCM,data:2F0o8PyAyvOLxTvaizZZZH7cvG8MQ3sacbcLMW7nkt2eRWavwOVtrQbGH8xiWg++Vgc5vzYoatJO9vK8oSiOzse2SitANKTu2CDIQGZd0ItHQERzqPd8oFfmKJCZkEkvuiuem5eyKN8U4Q9isaNt1R7YqTXb4x9ZnT/RdbNCYxg=,iv:mGfqN6EVtC/0w2cWo59IghDBw0PBmr8OuLA55ZCd/HY=,tag:pLaULmezvO8PYULyYIPmsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
