apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:l+xsDm5nvZMLcdSPRC1AdM4jnhKqb/iUfgAyE5tf8Cw0Yob+pXHx12FmROzDDxkfLOoJ4xEq8O/J67OvLXe3ShvrUSYQqCxJmHp8,iv:DNb2Ski9qHRK5q3zd2Wg+KhXfs/9HPiZ2mBk29+jyM8=,tag:Rl2Z3mofnymgQsW+vWpH+A==,type:str]
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRjdKYjM0VmkvSHBJcU5E
        dldvWkNVNjNhS0lWVGEzS2ZXZ0xZVUU2MXh3CnlsV2tralppdk56TVY2U1lORW5j
        U0hpV1JKQzVCQVJvbGlWWjVhbmVJK2sKLS0tIFFtL1FIRHg1eXdlU1BUcVdlSlBD
        WnpVT1BoM0pSNHNKZTk0SUUxV24ya0EKiTgXP36PVc8G506AC2wMmKBdHCwKFGfn
        CWaw2yXcfG6/xIyzIgxqtTtlQTYW4chnXtCx6dvIY8x1DTf7xsAcag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T14:17:32Z"
  mac: ENC[AES256_GCM,data:d0U/T00UTOIYSW3YF9g3NFoI+ggzAPbQ9/Ml57RckpWIJemWn+7f5CZ4eJwXkz1zGpLWKYEpZbc0QjaDMP+2liqunC5Cz2OwFP1lsCQHbLriG0qqSmSNe1JA92EjytAWtPPrbWz+Rz93V3bcUFV2M98e55fZ492rPDepI5Uow8Y=,iv:Zw9xi6LCwPPgsCVSEh15+GPkbDmSn1PtajdNOg5w76g=,tag:jn1MOXt/nQPKqikrt4y0SQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
