apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.aknuk.dev
      recordType: CNAME
      targets:
        - d5d51ce4-3a6c-460d-b378-6975de02f697.cfargotunnel.com
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRKzdFVnRxekdTa1F2SDA3
        NEtCMWpLa0hNVWhUUG84UnVvS1ZpazBFN2dNClJIay9HT2NCMXBpa3J3blloTXU1
        Mktsbm5qdGV1dmd0Y2kvNzhydGh2ZHcKLS0tIEpHaXkySlRkN2ZaQmxlVzhETWNH
        eUw1VXREOGdxTFkyMUdTcXA1ZXFTeTQK9Op8/+WqAPjHEy/W8Jq7T5zh/8KbgbeT
        1qc1wXPrcoeUcuB/Qshy0WEa6epOV4elOE6tq2If9bjOtEChVwPvsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:18:05Z"
  mac: ENC[AES256_GCM,data:ecGk5o0FEks6AItymZ8shezgKNOyZ3KXDKMiCZIurpdx7qsG3WJEpI29SkKrL63+Dc0+r0PWfN6zLxafJHqqCeJZIWng82ly4y+RPPqSO3qaUCRjXRbnAyjx7burrNF1KnvewXZCBGBx5a3u16H9mSLVYhj3txADJWZ3Oibvu4w=,iv:ARsR/4gfvmtlHNiWHIwgeSMsLhfiZ6UIkx8mShjFaHE=,tag:KlTn10S8biZhDt3cTccAQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
