apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.aknuk.dev
      recordType: CNAME
      targets:
        - d5d51ce4-3a6c-460d-b378-6975de02f697.cfargotunnel.com
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UjhBaGM3UmJjMzF0V3Nl
        d3YwQ1VjZDNKK1hva3JPUThnWmMyNGxxVFNrCldSMnhVallOWUt1ZWs2WUNhajVI
        dHBDNHVRbHl2NHptVWNsTU8zcFUxbEkKLS0tIFV3V3RjS3Rsci9DTlRJalVnSUp6
        dGNHUEtxTlcrS2VwMGEwLzQzV2dSRHMKiCfxoCJCcBg1mAPhAIcwWriWh5GOk3As
        sooeexBC9tqNUDxywSlhaGFj3UG7xIm/5p1dIEetb2zpQvbpY1BQqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T14:17:32Z"
  mac: ENC[AES256_GCM,data:iJkGudeIB/aaGTp0FLrtnHobR9A/hVmQqn1uLof++cIaG0Y7ZK7W/F17XggP19ZCpHLxMsHLEFkqBp6D48iHkoEe9OpdwagmLI8HT1oA/hVYcXSxeybw/0P8vF3CC6L2fl38m4yQigBAh/91MWwrScZl7I6rtsKtDFA+STUQH0s=,iv:GToCy2ufUb7By5EYxmVKgx3zXdr81dSwIhjwvKBSEAE=,tag:HY0Sj0k/2w9HC3+cYxEyDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
