fullnameOverride: k8s-gateway
domain: aknuk.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.201
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycC9zSVJsYy9NU1V2Yld2
        Tk83a3JmOHRXQmlDYTVSMmFXa0pqSzhENmlRCmJJUE9CVWNvbTFBSjVFcDlpYjdS
        WHFJTkZUTk9JMFFlV3dlZldKU2RsNGsKLS0tIDU0d0kza04zU2srZitxcE9naXgx
        Sng4UkJ6UG1FV2NkSE1hKzA5YkRMTTAKB+uKsgRM6tV/uxv9B1rhbhvP/0f28fti
        cUCh/MhrcL4Pg/OxaXFqOtF6UB+NKe4PTOPXs0Xgqq0y2IkgpdFlkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:18:05Z"
  mac: ENC[AES256_GCM,data:vBOPJ4T/EDBCnZ0/gJ6ZYkIIEOzpeLnNXr9Cwo8WA2Coscrhq7Mt/qz86eVEl3uCyuZgKbSCHvBcj4pXKY7+kyDhDog/j5AubH/gDKy4y96rIWwTbr6859W/L7xrMMLnme8/OCTDYlq3CQacim0IHLLg3RkaFbEIw/JNGR94Coc=,iv:p3+ggxXowQwAxBrrcCdMeaAkaBUOT7vccbCr5oqyIKE=,tag:Jn9KTjKRqtPvLQN9YLIX4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
