# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aknuk-dev-production
spec:
  secretName: aknuk-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: aknuk.dev
  dnsNames:
    - aknuk.dev
    - '*.aknuk.dev'
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc0VwQm5BczVQVU9Wa3FL
        U0xQdlJpcEdyc3ExbHVFN0xiOWpTUVNHdkJrCkFIL0EvVGhCMGV1T2E1ekRXa1ZL
        WjhPY3pkZXdlZDRMZzhNbXhuSUxLblkKLS0tIGJjZ1hpZWZ5dlN1ditjNS9nT0d1
        U3NOZFJjV3JxUEY1emNoQ0JrbklzYTgKOylvhlvXuCMJRcXX5c4MJc+NwuopL2kR
        nyGnuCezQcJiHyTpR/hmJVLZIDdJt89gmk+J5KPBuIHZqU6Y5NbBjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:44:11Z"
  mac: ENC[AES256_GCM,data:OwoEEOSIq60tEFxe7DVyIDfRRNxM0ENeT9ftAawphn9uBVCJmEcnmxsMeGorkRGLnIYK/NHh9v1ZPSBLNifEBGHDpnTXYI8R5VFrTxQ8I9sOnQ0rbiMgOf5kF2FOsYqcNrqm3MtC0D/X4K4oi8/Wo4toMa7wnYZWkRkw9vzu9r0=,iv:GJ25XeL1wpeVIFgSs8AtwdJ1jprCUa+LRrqV3jHyUcw=,tag:vt/5yUqbfGvF9xVI1ydCiA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
