# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.aknuk.dev
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.88.103
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.aknuk.dev
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: '*.aknuk.dev'
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: '*.aknuk.dev'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: aknuk-dev-production-tls
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSXU4dm8xbjYyOEhEVHg2
        TnhoK0duQ3VxS2hmVjVFb0VQcjVVM0dOYUZRCnBtV1lIM0F5dzF0V2kyVEtnc3FI
        dHM0SC9PV2pJTHpIZE5jUENCZzZZSm8KLS0tIENpdithUCtLbldSN250Tk1iNG9r
        UlA5Nllwc0UrQjg0ak1GSlErNmpFeG8KGIhBeNKMPCOF3c/JRKQgQoVdvSqBLyzL
        f6o0xEYfxrNBhkgvymAmeMMUFF88OYyO24pQHW35uXuRPyT2jjbX0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T15:47:26Z"
  mac: ENC[AES256_GCM,data:QoOXPLRGQHx3mmNg4xv+cjBx6hfQwrlVbd9ijjlghKxvzqZGbYyOvp1NQrEekx9Us3VZy6l2Kj/fOxt8R7Vvoy/m72RlRKmaVFxCD9cxDB/VXtS6l00zAikXxaKuJbBZH5XlQeRfRXeP7GRNWhMKVabaE9m9Gf5/LFAwBEIV7Fg=,iv:8z8fMwGBZpWf4W5Gq2JIoEpHCoW8/elfjMsvL5gkeKY=,tag:Y14tGHcVED2oCGxbt19Prw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
