# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.aknuk.dev
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.8.202
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.aknuk.dev
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: '*.aknuk.dev'
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: '*.aknuk.dev'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: aknuk-dev-production-tls
sops:
  age:
    - recipient: age1ptne7j9y9v4vdkjaj4e97kk6cexs0vtfn8lswryc584xguudj4usfga4el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNW1LL09icDhaVmJCRVFR
        Sk9vSjZUUXhCNXJSTUpEQ2dsSHE1TmtTUzFvCmhIK2lMaEl0c0Yyd2I0cW9RRGFN
        bStEQTVuaThlRGQ2ajJBdXRFeGlTTmMKLS0tIHdoMlVvTWswWjIyc2JpdFNYMjBZ
        cDg3NGlzY2pUdW9UbnNGN1F4WFE2cWsK/oOa13HthcIw8KIcCvp3L1ibKfPIk/nv
        8EOwj8tIYq/Z6eoaj68fbhmetoN9BS47MJN8/nMabfckefbbUE1Y0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T13:44:11Z"
  mac: ENC[AES256_GCM,data:bk9pJJM3SBbNb4mEMb4ljWRxVVACO0d2na7QJVgG7MHotYwAXXj30+orVm0AHZ7ugHTMs36cj1NpOWYhxedNRwxvtrbStiLme1XLJTNjwS+ypJuqcS4mqqZW6CU0idlREnO/K0EyeEZRfd88T6xskvCNu476UlE3YaQ6ry4UPkg=,iv:qcSldHBuWSOIESEx8oOWOQwJmXWlyMo0yJf+o7refz0=,tag:ouP9OKz9XoCqNG1kFITTKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
